name: flutter_joy_ble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  #sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.0.4
  cupertino_icons: ^1.0.6
  control_pad_plus: ^0.1.0
  flutter_blue: ^0.8.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  very_good_analysis: ^5.0.0
  flutter_bloc: ^8.1.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
